import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

// Check TINYCODE_ first, then fall back to OPENCODE_ for backward compatibility
function env(tinyKey: string, openKey: string): string | undefined {
  return process.env[tinyKey] ?? process.env[openKey]
}

function envTruthy(tinyKey: string, openKey: string): boolean {
  return truthy(tinyKey) || truthy(openKey)
}

const TINYCODE_EXPERIMENTAL = truthy("TINYCODE_EXPERIMENTAL") || truthy("OPENCODE_EXPERIMENTAL")
const copy = process.env["TINYCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"] ?? process.env["OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

function enabledByExperimental(tinyKey: string, openKey: string) {
  if (process.env[tinyKey] !== undefined) return truthy(tinyKey)
  if (process.env[openKey] !== undefined) return truthy(openKey)
  return TINYCODE_EXPERIMENTAL
}

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  TINYCODE_AUTO_HEAP_SNAPSHOT: envTruthy("TINYCODE_AUTO_HEAP_SNAPSHOT", "OPENCODE_AUTO_HEAP_SNAPSHOT"),
  TINYCODE_GIT_BASH_PATH: env("TINYCODE_GIT_BASH_PATH", "OPENCODE_GIT_BASH_PATH"),
  TINYCODE_CONFIG: env("TINYCODE_CONFIG", "OPENCODE_CONFIG"),
  TINYCODE_CONFIG_CONTENT: env("TINYCODE_CONFIG_CONTENT", "OPENCODE_CONFIG_CONTENT"),
  TINYCODE_DISABLE_AUTOUPDATE: envTruthy("TINYCODE_DISABLE_AUTOUPDATE", "OPENCODE_DISABLE_AUTOUPDATE"),
  TINYCODE_ALWAYS_NOTIFY_UPDATE: envTruthy("TINYCODE_ALWAYS_NOTIFY_UPDATE", "OPENCODE_ALWAYS_NOTIFY_UPDATE"),
  TINYCODE_DISABLE_PRUNE: envTruthy("TINYCODE_DISABLE_PRUNE", "OPENCODE_DISABLE_PRUNE"),
  TINYCODE_DISABLE_TERMINAL_TITLE: envTruthy("TINYCODE_DISABLE_TERMINAL_TITLE", "OPENCODE_DISABLE_TERMINAL_TITLE"),
  TINYCODE_SHOW_TTFD: envTruthy("TINYCODE_SHOW_TTFD", "OPENCODE_SHOW_TTFD"),
  TINYCODE_DISABLE_AUTOCOMPACT: envTruthy("TINYCODE_DISABLE_AUTOCOMPACT", "OPENCODE_DISABLE_AUTOCOMPACT"),
  TINYCODE_DISABLE_MODELS_FETCH: envTruthy("TINYCODE_DISABLE_MODELS_FETCH", "OPENCODE_DISABLE_MODELS_FETCH"),
  TINYCODE_DISABLE_MOUSE: envTruthy("TINYCODE_DISABLE_MOUSE", "OPENCODE_DISABLE_MOUSE"),
  TINYCODE_FAKE_VCS: env("TINYCODE_FAKE_VCS", "OPENCODE_FAKE_VCS"),
  TINYCODE_SERVER_PASSWORD: env("TINYCODE_SERVER_PASSWORD", "OPENCODE_SERVER_PASSWORD"),
  TINYCODE_SERVER_USERNAME: env("TINYCODE_SERVER_USERNAME", "OPENCODE_SERVER_USERNAME"),

  // New tinycode-specific env vars
  TINYCODE_OLLAMA_HOST: process.env["TINYCODE_OLLAMA_HOST"] ?? "http://localhost:11434",
  TINYCODE_VLLM_HOST: process.env["TINYCODE_VLLM_HOST"] ?? "http://localhost:8000",

  // Experimental
  TINYCODE_EXPERIMENTAL_FILEWATCHER: Config.boolean("TINYCODE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.orElse(() => Config.boolean("OPENCODE_EXPERIMENTAL_FILEWATCHER")),
    Config.withDefault(false),
  ),
  TINYCODE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("TINYCODE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.orElse(() => Config.boolean("OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER")),
    Config.withDefault(false),
  ),
  TINYCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("TINYCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT") || truthy("OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  TINYCODE_MODELS_URL: env("TINYCODE_MODELS_URL", "OPENCODE_MODELS_URL"),
  TINYCODE_MODELS_PATH: env("TINYCODE_MODELS_PATH", "OPENCODE_MODELS_PATH"),
  TINYCODE_DB: env("TINYCODE_DB", "OPENCODE_DB"),

  TINYCODE_WORKSPACE_ID: env("TINYCODE_WORKSPACE_ID", "OPENCODE_WORKSPACE_ID"),
  TINYCODE_EXPERIMENTAL_WORKSPACES: enabledByExperimental("TINYCODE_EXPERIMENTAL_WORKSPACES", "OPENCODE_EXPERIMENTAL_WORKSPACES"),
  TINYCODE_EXPERIMENTAL_SESSION_SWITCHER: enabledByExperimental("TINYCODE_EXPERIMENTAL_SESSION_SWITCHER", "OPENCODE_EXPERIMENTAL_SESSION_SWITCHER"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get TINYCODE_DISABLE_PROJECT_CONFIG() {
    return truthy("TINYCODE_DISABLE_PROJECT_CONFIG") || truthy("OPENCODE_DISABLE_PROJECT_CONFIG")
  },
  get TINYCODE_TUI_CONFIG() {
    return process.env["TINYCODE_TUI_CONFIG"] ?? process.env["OPENCODE_TUI_CONFIG"]
  },
  get TINYCODE_CONFIG_DIR() {
    return process.env["TINYCODE_CONFIG_DIR"] ?? process.env["OPENCODE_CONFIG_DIR"]
  },
  get TINYCODE_PURE() {
    return truthy("TINYCODE_PURE") || truthy("OPENCODE_PURE")
  },
  get TINYCODE_PERMISSION() {
    return process.env["TINYCODE_PERMISSION"] ?? process.env["OPENCODE_PERMISSION"]
  },
  get TINYCODE_PLUGIN_META_FILE() {
    return process.env["TINYCODE_PLUGIN_META_FILE"] ?? process.env["OPENCODE_PLUGIN_META_FILE"]
  },
  get TINYCODE_CLIENT() {
    return process.env["TINYCODE_CLIENT"] ?? process.env["OPENCODE_CLIENT"] ?? "cli"
  },
}
